clear; 
[trainset, trainlabel]=loadSubset(0);
[testset_1,testlabel_1] = loadSubset(1);
[testset_2,testlabel_2] = loadSubset(2);
[testset_3,testlabel_3] = loadSubset(3);
[testset_4,testlabel_4] = loadSubset(4);

% knn for testset1 
%l1 norm 
[predicted_testset_1_1_l1, error_rate_testset_1_1_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,1,1);
[predicted_testset_1_3_l1, error_rate_testset_1_3_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,3,1);
[predicted_testset_1_5_l1, error_rate_testset_1_5_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,5,1);

%l2 norm
[predicted_testset_1_1_l2, error_rate_testset_1_1_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,1,2);
[predicted_testset_1_3_l2, error_rate_testset_1_3_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,3,2);
[predicted_testset_1_5_l2, error_rate_testset_1_5_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_1,...
    testlabel_1,5,2);

% knn for testset2
%l1 norm 
[predicted_testset_2_1_l1, error_rate_testset_2_1_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,1,1);
[predicted_testset_2_3_l1, error_rate_testset_2_3_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,3,1);
[predicted_testset_2_5_l1, error_rate_testset_2_5_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,5,1);

%l2 norm 
[predicted_testset_2_1_l2, error_rate_testset_2_1_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,1,2);
[predicted_testset_2_3_l2, error_rate_testset_2_3_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,3,2);
[predicted_testset_2_5_l2, error_rate_testset_2_5_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_2,...
    testlabel_2,5,2);

% knn for testset3
%l1 norm
[predicted_testset_3_1_l1, error_rate_testset_3_1_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,1,1);
[predicted_testset_3_3_l1, error_rate_testset_3_3_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,3,1);
[predicted_testset_3_5_l1, error_rate_testset_3_5_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,5,1);

%l2 norm 
[predicted_testset_3_1_l2, error_rate_testset_3_1_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,1,2);
[predicted_testset_3_3_l2, error_rate_testset_3_3_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,3,2);
[predicted_testset_3_5_l2, error_rate_testset_3_5_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_3,...
    testlabel_3,5,2);

% % knn for testset4
%l1 norm
[predicted_testset_4_1_l1, error_rate_testset_4_1_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,1,1);
[predicted_testset_4_3_l1, error_rate_testset_4_3_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,3,1);
[predicted_testset_4_5_l1, error_rate_testset_4_5_l1] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,5,1);

%l2 norm 
[predicted_testset_4_1_l2, error_rate_testset_4_1_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,1,2);
[predicted_testset_4_3_l2, error_rate_testset_4_3_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,3,2);
[predicted_testset_4_5_l2, error_rate_testset_4_5_l2] = knn_recognition_error_rate(trainset, trainlabel, testset_4,...
    testlabel_4,5,2);
